version: '2'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - /Users/rhonnav/auditNG/elasticsearch/elasticsearch.yml:/Users/rhonnav/auditNG/elasticsearch/config/elasticsearch.yml
    networks:
      default:
        aliases:
          - esnet
  elastalert:
    build:
      context: .
      dockerfile: elastalert.Dockerfile
    networks:
      default:

    volumes:
      - /Users/rhonnav/auditNG/elastalert/

networks:
  default:

volumes:
  gf_data:
  postgres_data:
  es_data:
  web_media_root:
  web_static_root:
