version: '2'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    volumes:
      - es_data:/Users/rhonnav/auditNG/elasticsearch/data
      - /Users/rhonnav/auditNG/elasticsearch/elasticsearch.yml:/Users/rhonnav/auditNG/elasticsearch/config/elasticsearch.yml
    networks:
      default:
        aliases:
          - esnet
  kibana:
    image: kibana:5.5.1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    networks:
      default:
        aliases:
          - esnet
networks:
  default:

volumes:
  gf_data:
  postgres_data:
  es_data:
  web_media_root:
  web_static_root:
